import type { Category, Product, ProductVariant, Store } from './types'

export const store: Store = {
  id: 'store-1',
  name: 'Solari Indumentaria',
  slug: 'solari',
  logo_url: '/images/logo.jpg',
  whatsapp_number: '5491112345678', // Placeholder - update with real number
  instagram_url: 'https://instagram.com/solari.ind',
  address: 'Buenos Aires, Argentina',
  currency: 'ARS',
  active: true,
}

export const categories: Category[] = [
  {
    id: 'cat-1',
    store_id: 'store-1',
    name: 'Remeras',
    slug: 'remeras',
    description: 'Remeras básicas y estampadas',
    image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=500&fit=crop',
    sort_order: 1,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    store_id: 'store-1',
    name: 'Pantalones',
    slug: 'pantalones',
    description: 'Jeans, joggers y pantalones de vestir',
    image_url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=500&fit=crop',
    sort_order: 2,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    store_id: 'store-1',
    name: 'Camperas',
    slug: 'camperas',
    description: 'Camperas y abrigos',
    image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=500&fit=crop',
    sort_order: 3,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    store_id: 'store-1',
    name: 'Camisas',
    slug: 'camisas',
    description: 'Camisas casual y formales',
    image_url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=500&fit=crop',
    sort_order: 4,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-5',
    store_id: 'store-1',
    name: 'Vestidos',
    slug: 'vestidos',
    description: 'Vestidos para toda ocasión',
    image_url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=500&fit=crop',
    sort_order: 5,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-6',
    store_id: 'store-1',
    name: 'Accesorios',
    slug: 'accesorios',
    description: 'Cinturones, gorras y más',
    image_url: 'https://images.unsplash.com/photo-1523779105320-d1cd346ff52b?w=400&h=500&fit=crop',
    sort_order: 6,
    active: true,
    created_at: new Date().toISOString(),
  },
]

const sizeVariants = (productId: string): ProductVariant[] => [
  { id: `${productId}-s`, product_id: productId, type: 'size', label: 'S', value: 's', price_override: null, stock: 5, active: true, sort_order: 1 },
  { id: `${productId}-m`, product_id: productId, type: 'size', label: 'M', value: 'm', price_override: null, stock: 8, active: true, sort_order: 2 },
  { id: `${productId}-l`, product_id: productId, type: 'size', label: 'L', value: 'l', price_override: null, stock: 6, active: true, sort_order: 3 },
  { id: `${productId}-xl`, product_id: productId, type: 'size', label: 'XL', value: 'xl', price_override: null, stock: 3, active: true, sort_order: 4 },
]

export const products: Product[] = [
  // MUJER
  {
    id: 'prod-1',
    store_id: 'store-1',
    category_id: 'cat-5',
    brand_id: null,
    name: 'Vestido Midi Elegante',
    slug: 'vestido-midi-elegante',
    description: 'Vestido midi con corte elegante, perfecto para ocasiones especiales. Confeccionado en tela premium con caída suave.',
    base_price: 45900,
    compare_at_price: 52900,
    active: true,
    sort_order: 1,
    gender: 'mujer',
    is_made_to_order: false,
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&h=1000&fit=crop',
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: categories.find(c => c.id === 'cat-5'),
    variants: sizeVariants('prod-1'),
  },
  {
    id: 'prod-2',
    store_id: 'store-1',
    category_id: 'cat-1',
    brand_id: null,
    name: 'Remera Oversize Premium',
    slug: 'remera-oversize-premium',
    description: 'Remera oversize de algodón peinado 100%. Corte relajado y cómodo para el día a día.',
    base_price: 18900,
    compare_at_price: null,
    active: true,
    sort_order: 2,
    gender: 'mujer',
    is_made_to_order: false,
    images: [
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1618354691438-25bc04584c23?w=800&h=1000&fit=crop',
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: categories.find(c => c.id === 'cat-1'),
    variants: sizeVariants('prod-2'),
  },
  {
    id: 'prod-3',
    store_id: 'store-1',
    category_id: 'cat-2',
    brand_id: null,
    name: 'Jean Mom Fit',
    slug: 'jean-mom-fit',
    description: 'Jean mom fit de tiro alto con lavado claro. El corte perfecto que nunca pasa de moda.',
    base_price: 35900,
    compare_at_price: 42900,
    active: true,
    sort_order: 3,
    gender: 'mujer',
    is_made_to_order: false,
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?w=800&h=1000&fit=crop',
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: categories.find(c => c.id === 'cat-2'),
    variants: sizeVariants('prod-3'),
  },
  {
    id: 'prod-4',
    store_id: 'store-1',
    category_id: 'cat-3',
    brand_id: null,
    name: 'Blazer Oversize',
    slug: 'blazer-oversize',
    description: 'Blazer oversize estructurado en color neutro. Ideal para armar looks sofisticados.',
    base_price: 62900,
    compare_at_price: null,
    active: true,
    sort_order: 4,
    gender: 'mujer',
    is_made_to_order: true,
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&h=1000&fit=crop',
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: categories.find(c => c.id === 'cat-3'),
    variants: sizeVariants('prod-4'),
  },
  // HOMBRE
  {
    id: 'prod-5',
    store_id: 'store-1',
    category_id: 'cat-4',
    brand_id: null,
    name: 'Camisa Lino Natural',
    slug: 'camisa-lino-natural',
    description: 'Camisa de lino 100% con corte regular. Fresca y elegante para cualquier ocasión.',
    base_price: 38900,
    compare_at_price: 45900,
    active: true,
    sort_order: 5,
    gender: 'hombre',
    is_made_to_order: false,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800&h=1000&fit=crop',
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: categories.find(c => c.id === 'cat-4'),
    variants: sizeVariants('prod-5'),
  },
  {
    id: 'prod-6',
    store_id: 'store-1',
    category_id: 'cat-1',
    brand_id: null,
    name: 'Remera Básica Algodón',
    slug: 'remera-basica-algodon',
    description: 'Remera básica de algodón premium. Un esencial para tu guardarropa.',
    base_price: 15900,
    compare_at_price: null,
    active: true,
    sort_order: 6,
    gender: 'hombre',
    is_made_to_order: false,
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1622445275576-721325763afe?w=800&h=1000&fit=crop',
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: categories.find(c => c.id === 'cat-1'),
    variants: sizeVariants('prod-6'),
  },
  {
    id: 'prod-7',
    store_id: 'store-1',
    category_id: 'cat-2',
    brand_id: null,
    name: 'Jean Slim Fit Negro',
    slug: 'jean-slim-fit-negro',
    description: 'Jean slim fit en negro con elastano para mayor comodidad. Corte moderno y versátil.',
    base_price: 32900,
    compare_at_price: null,
    active: true,
    sort_order: 7,
    gender: 'hombre',
    is_made_to_order: false,
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&h=1000&fit=crop',
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: categories.find(c => c.id === 'cat-2'),
    variants: sizeVariants('prod-7'),
  },
  {
    id: 'prod-8',
    store_id: 'store-1',
    category_id: 'cat-3',
    brand_id: null,
    name: 'Campera Cuero Sintético',
    slug: 'campera-cuero-sintetico',
    description: 'Campera de cuero sintético premium con cierre metálico. Estilo atemporal.',
    base_price: 72900,
    compare_at_price: 85900,
    active: true,
    sort_order: 8,
    gender: 'hombre',
    is_made_to_order: false,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1520975954732-35dd22299614?w=800&h=1000&fit=crop',
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: categories.find(c => c.id === 'cat-3'),
    variants: sizeVariants('prod-8'),
  },
]

export function getProductsByGender(gender: 'mujer' | 'hombre' | 'todo'): Product[] {
  if (gender === 'todo') return products
  return products.filter(p => p.gender === gender || p.gender === 'unisex')
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug)
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id)
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('es-AR', {
    style: 'currency',
    currency: 'ARS',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price)
}
